# Basic Information 
title: Zhutao Li
position: M.S. Student
affiliation: Southern University of Science and Technology
email: 12433457 (at) mail.sustech.edu.cn

# Search Engine Optimization (SEO)
keywords: Brain-Computer Interface, BCI, Neural Signal Processing,Human-in-the-Loop (HITL) Control
description: Zhutao Li's Academic Homepage
canonical: https://ztgogoing.github.io/

# Links 
github_link: https://github.com/zTGogoing

# Images 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Sans Serif"

# Google Analytics ID (留空或填入你自己的ID，已注释掉作者默认ID以防数据混淆)
# google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
